title: Echo Mythos
description: Unseen Origins, Infinite Reflections
baseurl: "" # leave empty for root
url: "https://echomythos.github.io" # your live site address
theme: minima
header_pages:
  - index.md
  - videos.md
  - articles.md

collections:
  videos:
    output: true
    defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post_with_nav


