title: Echo Mythos
description: Unseen Origins, Infinite Reflections
baseurl: ""              # leave empty for root
url: "https://echomythos.github.io"
theme: minima

header_pages:
  - index.md
  - video.md            # <-- your page is singular "video.md"
  - articles.md

collections:
  videos:
    output: true

defaults:
  - scope:
      path: ""          # all files
      type: posts       # blog posts in _posts
    values:
      layout: post_with_nav
