title: Echo Mythos
description: Unseen Origins, Infinite Reflections
baseurl: ""
url: "https://echomythos.github.io"
theme: minima

header_pages:
  - index.md
  - videos.md
  - articles.md

collections:
  videos:
    output: true
    permalink: /videos/:name/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post_with_nav
