title: Echo Mythos
description: Unseen Origins, Infinite Reflections
baseurl: ""
url: "https://echom-ythos.com"
theme: minima



collections:
  videos:
    output: true
    permalink: /videos/:name/

include:
  - _videos

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post_with_nav

  - scope:
      path: "_videos"
      type: videos
    values:
      layout: video   # ← your clean layout

